In [1]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.19.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.5.20)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (0.1.2)

In [2]:
from datasets import load_dataset

In [3]:
dataset=load_dataset("CShorten/ML-ArXiv-Papers",split='train')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:124: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/986 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

ML-Arxiv-Papers.csv:   0%|          | 0.00/147M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/117592 [00:00<?, ? examples/s]

In [4]:
print(dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})

In [5]:
dataset[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'}

In [6]:
import pandas as pd

In [7]:
df=pd.DataFrame(dataset)
df

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...,...,...
117587,4995,NaN,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,4996,NaN,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,4997,NaN,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,4998,NaN,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,4999,NaN,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

In [8]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [9]:
df=df[['title','abstract']]

In [10]:
df

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...
117587,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

In [11]:
# Reduce the no of rows
df=df.head(15000)
df

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...
14995,Estimation of a Low-rank Topic-Based Model for...,We consider the problem of estimating the la...
14996,A Comparison of Audio Signal Preprocessing Met...,"In this paper, we empirically investigate th..."
14997,Implicit Regularization in Deep Learning,In an attempt to better understand generaliz...
14998,A Quasi-isometric Embedding Algorithm,The Whitney embedding theorem gives an upper...
14999,On Fairness and Calibration,The machine learning community has become in...

In [12]:
df.isnull().sum()

title       0
abstract    0
dtype: int64

In [13]:
df["paper_text"]=df["title"]+" "+df["abstract"]
df

/tmp/ipykernel_2791/3936252372.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["title"]+" "+df["abstract"]

,title,abstract,paper_text
0,Learning from compressed observations,The problem of statistical learning is to co...,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun...",Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...,Parametric Learning and Monte Carlo Optimizati...
...,...,...,...
14995,Estimation of a Low-rank Topic-Based Model for...,We consider the problem of estimating the la...,Estimation of a Low-rank Topic-Based Model for...
14996,A Comparison of Audio Signal Preprocessing Met...,"In this paper, we empirically investigate th...",A Comparison of Audio Signal Preprocessing Met...
14997,Implicit Regularization in Deep Learning,In an attempt to better understand generaliz...,Implicit Regularization in Deep Learning In ...
14998,A Quasi-isometric Embedding Algorithm,The Whitney embedding theorem gives an upper...,A Quasi-isometric Embedding Algorithm The Wh...
14999,On Fairness and Calibration,The machine learning community has become in...,On Fairness and Calibration The machine lear...

In [14]:
# // converting into dataframe
df[["paper_text"]].head()

                                          paper_text
0  Learning from compressed observations   The pr...
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3  A neural network approach to ordinal regressio...
4  Parametric Learning and Monte Carlo Optimizati...

In [15]:
type(df[["paper_text"]].head())

pandas.core.frame.DataFrame

In [16]:
print(df["paper_text"].iloc[0])

Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regression in Gaussian noise.

In [17]:
from sentence_transformers import SentenceTransformer

In [18]:
# 1. Load a pretrained Sentence Transformer model

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [19]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>

In [20]:
sample_text=df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'

In [21]:
# Remove \n(new line) so that model does not become confuse with \n
df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)
df

/tmp/ipykernel_2791/1813364570.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)

,title,abstract,paper_text
0,Learning from compressed observations,The problem of statistical learning is to co...,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun...",Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...,Parametric Learning and Monte Carlo Optimizati...
...,...,...,...
14995,Estimation of a Low-rank Topic-Based Model for...,We consider the problem of estimating the la...,Estimation of a Low-rank Topic-Based Model for...
14996,A Comparison of Audio Signal Preprocessing Met...,"In this paper, we empirically investigate th...",A Comparison of Audio Signal Preprocessing Met...
14997,Implicit Regularization in Deep Learning,In an attempt to better understand generaliz...,Implicit Regularization in Deep Learning In ...
14998,A Quasi-isometric Embedding Algorithm,The Whitney embedding theorem gives an upper...,A Quasi-isometric Embedding Algorithm The Wh...
14999,On Fairness and Calibration,The machine learning community has become in...,On Fairness and Calibration The machine lear...

In [22]:
df["paper_text"].iloc[0]

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regression in Gaussian noise. '

In [23]:
# Removed white spaces in front and last
df["paper_text"]=df["paper_text"].str.strip()

/tmp/ipykernel_2791/1640325731.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.strip()

In [24]:
df["paper_text"].iloc[0]

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regression in Gaussian noise.'

In [25]:
# 2. Calculate embeddings by calling model.encode()
embeddings = model.encode(sample_text)
print(embeddings.shape)
print(type(embeddings))

(384,)
<class 'numpy.ndarray'>

In [26]:
embeddings

array([-1.31564096e-01, -6.78266399e-03, -3.67611554e-03,  3.26515771e-02,
        1.12196416e-01,  1.22726746e-02,  9.81671885e-02, -9.00522992e-02,
        4.23116125e-02, -1.97734833e-02, -3.30841690e-02,  7.45294765e-02,
        1.06320381e-01, -2.06042901e-02, -2.05210559e-02,  1.69492734e-03,
        7.08195344e-02,  5.85445389e-02, -1.12319119e-01,  2.08247416e-02,
        5.69254383e-02,  2.01577954e-02,  2.58310959e-02,  3.21703032e-02,
        1.05137639e-01, -9.67676342e-02,  2.70080194e-02, -2.34509036e-02,
       -4.54967804e-02, -1.01369917e-02, -1.79485492e-02, -4.81442735e-02,
        1.07765235e-02, -3.75906937e-02,  1.94348078e-02,  3.71518917e-02,
        2.96784397e-02,  4.33094054e-02,  4.37321328e-02,  3.70486639e-02,
       -1.82594243e-03,  4.55183210e-03, -7.99066573e-03,  3.03736813e-02,
       -1.43779954e-02,  3.79514731e-02,  5.95915988e-02, -2.58335639e-02,
       -6.52157590e-02,  5.90026751e-02, -2.10713428e-02,  7.35942200e-02,
       -5.72010614e-02,  2.94061168e-03,  7.67515041e-03, -3.33416015e-02,
       -2.41654795e-02, -2.09911615e-02, -4.76784147e-02,  1.42029971e-01,
       -4.16863151e-02, -2.28165630e-02, -1.45359263e-02, -4.39256663e-03,
       -6.80174604e-02, -2.55158730e-03,  7.34624565e-02,  4.29371521e-02,
       -3.04794312e-02,  5.82109131e-02, -8.45503658e-02, -5.60204033e-03,
       -9.26086232e-02,  5.90392165e-02,  1.99682508e-02, -1.46549465e-02,
        8.56686234e-02,  3.43410075e-02,  4.26304387e-03, -2.55769230e-02,
       -2.92939115e-02,  2.88600195e-03,  3.02557927e-02, -5.09372614e-02,
        3.13304402e-02, -1.24026472e-02,  1.93743203e-02,  7.15281740e-02,
        3.50777917e-02,  4.40817233e-03, -1.08218893e-01, -2.98317727e-02,
       -6.13419674e-02,  4.19662185e-02,  4.72577177e-02, -5.66610694e-02,
        6.82019591e-02, -7.44092464e-02,  9.27868038e-02,  9.60959345e-02,
       -6.80272877e-02,  1.62349537e-03,  4.31859270e-02, -3.07624172e-02,
        1.11809345e-02, -8.54723826e-02,  2.37832665e-02,  1.73624773e-02,
        5.39869023e-03,  1.58846974e-02,  4.44358401e-03, -1.15580717e-02,
       -9.76492744e-03, -7.40204891e-03, -1.88762192e-02, -3.39675322e-02,
       -4.86566871e-02,  4.36526947e-02, -1.04922511e-01, -8.63315240e-02,
       -4.52507772e-02, -7.29720220e-02, -2.08166596e-02,  3.65954190e-02,
       -8.82896595e-03, -2.35994346e-02, -4.47208323e-02,  1.54469435e-33,
        2.61055939e-02,  5.34729399e-02, -3.32894251e-02, -4.06732634e-02,
        2.65871175e-02,  8.22318271e-02, -7.54072098e-03, -1.62800876e-04,
        6.65079951e-02,  4.61811945e-02, -4.74173911e-02, -5.05927987e-02,
       -3.38295475e-02,  4.62175682e-02,  4.43545207e-02,  4.41354960e-02,
       -7.10298866e-02,  7.09743202e-02,  1.83767695e-02, -7.27372766e-02,
        7.00070933e-02, -2.09407806e-02, -5.53729497e-02, -4.75663356e-02,
       -4.31161933e-02, -5.32935597e-02,  2.69052514e-04, -3.83734368e-02,
        1.12205260e-02,  1.13959108e-02, -5.69416136e-02, -3.37940594e-03,
        1.03546835e-01, -8.47086757e-02,  3.53648420e-03, -5.72200790e-02,
        1.27505073e-02, -5.53163327e-03, -8.56065825e-02,  3.96663807e-02,
        2.25464292e-02,  4.99202013e-02,  4.13550548e-02, -2.60567125e-02,
       -5.83662651e-02, -7.51372352e-02,  1.08070455e-01,  6.15552999e-04,
       -9.01391208e-02, -1.32652506e-01, -2.54444475e-03, -3.37497890e-02,
       -9.57633182e-02,  2.57432461e-04,  1.16858846e-02,  2.23589987e-02,
        4.88692708e-02, -4.24660146e-02, -2.45967302e-02,  8.56855512e-02,
       -8.03445503e-02,  3.33040915e-02,  5.40195554e-02, -3.71836275e-02,
        2.11825653e-04,  1.86595805e-02,  3.10018621e-02, -5.36220260e-02,
        5.17720506e-02, -1.01843230e-01,  3.34464870e-02, -4.58090147e-03,
       -2.21982598e-02, -5.00102527e-02,  3.52232940e-02,  1.97152533e-02,
        1.44824926e-02, -6.63909968e-03, -1.26853054e-02, -1.63106353e-03,
       -4.83979098e-02, -4.59996425e-02, -1.93057656e-02, -2.97056921e-02,
       -5.00632338e-02,  3.04493047e-02,  1.81869287e-02, -4.53428216e-02,
       -4.88784164e-02,  1.22220418e-03, -1.06096022e-01, -3.71800996e-02,
       -7.55688176e-02, -4.81151640e-02,  2.25064009e-02, -2.23424595e-33,
       -2.21983828e-02,  8.51171017e-02,  2.62743942e-02,  5.43513559e-02,
       -1.57290157e-02, -1.96614843e-02, -2.73119509e-02,  2.96456274e-02,
       -4.53336583e-03, -8.33163559e-02, -9.22681540e-02, -4.08937819e-02,
        7.32074603e-02,  4.30881493e-02, -7.74768963e-02,  7.20389709e-02,
       -1.40663600e-02,  4.46009599e-02, -4.19447348e-02,  3.33845690e-02,
        2.91045606e-02,  3.20830345e-02,  2.09529325e-02,  2.23059859e-02,
        4.44135591e-02,  2.03914754e-02, -5.60238026e-02,  1.84909612e-01,
        2.28254497e-02, -7.39138667e-03, -4.18754295e-02, -7.15966672e-02,
       -6.42080531e-02, -6.63447380e-02, -2.05955114e-02,  1.06428731e-02,
        5.02156466e-03,  6.77870885e-02, -7.12078512e-02,  1.02496609e-01,
        9.44258943e-02,  3.30481939e-02, -5.00413626e-02,  2.62115058e-02,
        5.58213815e-02, -6.59461766e-02,  1.79097280e-02, -1.04770074e-02,
        7.34620541e-02, -2.46885954e-03,  3.85357551e-02,  4.46167700e-02,
       -2.85523422e-02,  9.08054486e-02, -7.84086436e-03, -2.77605653e-03,
       -9.57009941e-02, -1.16200401e-02,  5.25497720e-02,  9.29363593e-02,
       -6.14788337e-03,  8.09928868e-03, -6.72860369e-02,  8.18502530e-02,
        3.28589207e-03, -3.50581408e-02, -1.84767209e-02, -8.98536528e-05,
        7.32783079e-02,  9.57325399e-02,  4.15686145e-02, -6.18869476e-02,
        2.83940528e-02,  4.25410196e-02,  1.89858470e-02,  1.06751388e-02,
        2.51713898e-02,  3.08218487e-02, -6.59718513e-02,  8.87987539e-02,
        3.82416770e-02,  9.21778977e-02,  5.19544929e-02,  2.64026923e-03,
        1.49982981e-03,  5.44706956e-02,  7.31121972e-02, -8.08750861e-04,
        7.52013698e-02, -1.16245180e-01,  1.17986677e-02,  6.28149658e-02,
       -3.60430814e-02,  2.93700807e-02, -1.52511885e-02, -4.79335220e-08,
       -5.37610017e-02, -2.84531899e-02,  2.40290184e-02, -7.81880841e-02,
        1.01736046e-01, -2.52304114e-02,  7.01656519e-03, -2.86817085e-03,
        2.01843735e-02, -3.77830528e-02,  7.34866261e-02, -1.10320840e-03,
       -7.07776099e-02, -4.50035073e-02, -2.81599611e-02,  1.05185295e-02,
       -3.94658605e-03,  3.17634642e-02,  2.70489622e-02,  2.42667086e-02,
        3.24969143e-02, -2.10961308e-02, -5.78849530e-03, -2.25947611e-02,
        2.25187745e-02, -6.81575611e-02,  3.87890264e-02, -2.75328364e-02,
        1.55410301e-02,  1.14076272e-01, -5.39854914e-02,  3.54755260e-02,
        7.14311823e-02, -5.83239943e-02,  4.58902912e-03,  1.56194773e-02,
        1.03841741e-02, -4.26567607e-02,  1.35176852e-02, -5.60860373e-02,
        1.86446011e-02, -1.47688445e-02, -4.86134700e-02, -1.01973629e-02,
        6.46221414e-02,  1.17162606e-02,  4.91274446e-02, -4.35938574e-02,
       -2.97330189e-02, -5.42692728e-02,  3.84951942e-02,  1.90192666e-02,
        6.83268011e-02, -4.08833437e-02,  4.66427878e-02,  3.03019583e-03,
       -1.16352392e-02, -5.24238087e-02, -3.03320792e-02,  2.34115124e-02,
        2.92671612e-03,  9.56124961e-02, -4.42394167e-02,  5.22624329e-03],
      dtype=float32)

In [27]:
embeddings[:16]

array([-0.1315641 , -0.00678266, -0.00367612,  0.03265158,  0.11219642,
        0.01227267,  0.09816719, -0.0900523 ,  0.04231161, -0.01977348,
       -0.03308417,  0.07452948,  0.10632038, -0.02060429, -0.02052106,
        0.00169493], dtype=float32)

In [28]:
# top 5 lekar usko list meh convert kar diya
sample_embedding=model.encode(df["paper_text"].head(5).to_list())
sample_embedding

array([[-0.1315641 , -0.00678266, -0.0036761 , ...,  0.09561252,
        -0.04423944,  0.00522624],
       [-0.03589668, -0.06343269, -0.00394966, ...,  0.07206137,
        -0.13262011, -0.00412079],
       [-0.08129284,  0.024103  , -0.08868261, ..., -0.04524419,
        -0.0476585 , -0.01549932],
       [-0.10218991, -0.06282566,  0.03273673, ..., -0.03118814,
         0.03174181,  0.03621249],
       [-0.08391042,  0.01838467, -0.01556663, ..., -0.01188403,
        -0.10644462,  0.00790998]], dtype=float32)

In [29]:
print(sample_embedding.shape)

(5, 384)

#Analysis

In [30]:
from sklearn.metrics.pairwise import cosine_similarity

In [31]:
# Cosine similarity expects 2D
# Here reshape(1,-1) --> take 1 row and adjust the columns to the remaining ones
similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[0].reshape(1,-1))
similarity

array([[1.0000001]], dtype=float32)

In [33]:
similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[1].reshape(1,-1))
similarity

array([[0.36625272]], dtype=float32)

In [34]:
# Calculating similarity for first 5
for i in range(1,5):
  sim=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[i].reshape(1,-1))
  print(sim)

[[0.36625272]]
[[0.33522844]]
[[0.15505108]]
[[0.37421533]]

#Generating the Embeddings for 15000

In [36]:
#Embeddings-->Batch Size-->Ram Consumption Less
embedding=model.encode(df["paper_text"].to_list(),batch_size=32,show_progress_bar=True)

Batches:   0%|          | 0/469 [00:00<?, ?it/s]

In [37]:
print(embedding.shape)
print(type(embedding))
print(embedding.dtype)

(15000, 384)
<class 'numpy.ndarray'>
float32

FAISS --> It creates a special search structure

Cosine Similarity --> dot product hota hai

FAISS --> Inner product hota hai

L2 Normalization

In [38]:
!pip install faiss-cpu

Collecting faiss-cpu
  Downloading faiss_cpu-1.14.3-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)
Downloading faiss_cpu-1.14.3-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 39.2 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.14.3

In [39]:
import faiss

In [40]:
# Normalise embedding
faiss.normalize_L2(embedding)

In [41]:
# Create index
# Here IP means Inner Product it means it creates inner product for all embeddings
index=faiss.IndexFlatIP(384)
index

In [43]:
# Add the L2 normalized embeddings to the FAISS index.
# This prepares the index for efficient similarity searches.
index.add(embedding)

In [44]:
print(index.ntotal)

30000

In [45]:
# Create embedding for a query
query="deep learning for medical image analysis"
query_embedding=model.encode([query])
print(query_embedding.shape)

(1, 384)

In [46]:
# Normalize the query_embedding
faiss.normalize_L2(query_embedding)

In [47]:
# To search how closely our query matches with the stored vectors of the research papers
D,I=index.search(query_embedding,5)
print(D) # Similarity Score --> tells us the similarity score between our query nd the reseach papers stored in the FAISS
print(I) # Indices --> It tells konse paper no seh it is similar

[[0.6807244  0.6807244  0.67092204 0.67092204 0.65219975]]
[[25466 10466 28730 13730 26873]]